## Why data strategy will save machine intelligence
![]({{site.baseurl}}//1-Qjwfm3rbG_TAwcQfVXiNdw.jpeg)
After a few months of news on how Watson is evolving into Terminator 10 and DeepMind is going to solve world hunger, the hype around AI is beginning to wane. First, investors pointed to the commoditization of developer tools and horizontal platforms, then they caught onto concerns about algorithmic risk and bias, now they are fretting about the interpretability of deep learning. My best guess is that the next wave of critics will highlight obstacles around deployment, performance management, and debugging.

While these hurdles should not be ignored, they are not the primary issues impeding adoption of machine intelligence solutions. The most significant barrier is the way in which the enterprise approaches data.
Generally, enterprises [mis]use data in three ways: 1) to support operations; 2) to justify their intuition; 3) to cover their as#s. While most readers will understand these [mis]use cases, let me cathartically document these offenses:

_But first, a quick digression: For those of you who don’t know me, my background is in international security and military intelligence. As such, I like to [quote Sun Tzu] think about enterprise strategy in terms of Clausewitz’s Three Levels of War, wherein strategy concerns the ways and means by which we achieve national objectives; operations pertain to the design and execution of campaigns; and tactics refer to the applications of force and maneuvers that define our battles._

1. In military campaigns, cavalry typically played more tactical roles. While their reconnaissance might inform operations, their scouting and skirmishing rarely impact military strategy. Likewise, data analysts (and the data they collect or generate) are typically used to support operations. For example, a project manager has decided to launch a new service. He/she might use data to determine into which geographic market to launch. Likewise, a marketing specialist might try to study customer segments with data when planning a new social media campaign.  
Most enterprises understand how data can be used to direct decisions (i.e. operational guidance), but once the decision is made, the utility of the data (and the system which generated it) diminishes until the next critical operational decision arises (which may or may not require the same data feed and/or supporting infrastructure). For this reason, the land and expand strategy rarely works. You’re better off landing and going island hopping.  

1. We’ve all had gut feelings regarding the right option to chose. We can try to tell our supervisor that “we just know” or we can spend 30 minutes designing a beautiful Tableau chart that proves that our gut is correct. Visualizations are a great way to show what we already [think] know to be true.  
Earlier, I mentioned the interpretability problem (e.g. if deep learning is a black box, how can we explain its results). This is only a problem because humans still feel compelled to interpret data. While machine intelligence might provide a more objective answer, we want more control. We want the power to interpret data in a manner that proves we’re right.  

1. And lastly, the “I didn’t receive an alert” defense. We typically know of a set of things that might go wrong. We can use data, through dashboards and alerts, for situational awareness and to notify us when things go wrong. If issues do arise, and your dashboard and/or alerts didn’t tell you in advance, you won’t get fired. Monitoring is important, albeit limited in utility since most frequently the problems that occur are not those that we would predict.

Because enterprises use data tactically and operationally, adoption of machine intelligence solutions is slow. Open source tools are good enough to support well-scoped campaigns or limited engagements (if software is eating the world, open source is eating software). For those who fear open source offerings, consultants, or POCs that never turn into contracts, fit the bill. But who in their right mind would EVER pay for a subscription to solve a short-term pain? In fact, who would pay for any enterprise software that isn’t CRM or workflow automation?

To realize the true benefits of machine intelligence (and for machine intelligence startups to succeed), enterprises need to start thinking about data as a strategic asset. This means 2 things:

1. Define a data strategy that is aligned with your business’s mission, vision, and policy — not your operational requirements. This strategy should clarify the role and structure of your data team, how you will measure success (e.g. what are “big wins”?), and how you will set priorities. Since your data strategy should also specify what resources you need to support business objectives, you must also set a data acquisition strategy, which explains how you will acquire information. Sometimes collecting data through web scraping and machine/deep learning will be the right path forward. However, it may be more economical to buy data licenses or use crowdsourcing/outsourcing platforms.  
Once you’ve laid out your data and data acquisition strategy, you must determine the infrastructure and personnel required to implement and maintain it. Both should depend on the information you need and the channels through which you plan to get it. You should consider talent acquisition with respect to infrastructure and software selection. For example, if you have great data munging and pipelining software, you might be able to hire fewer, better data scientists (← whatever that means, but I’ll save that question for another diatribe).  

1. Think of data as something with currency — as something that can be sold or bartered. I cannot express how often I meet companies that have collected immensely valuable datasets that they could probably sell to someone else (remember when I said it’s sometimes more efficient to buy datasets, wouldn’t it be cool if we could all hold hands, sing kumbaya and exchange information?). Equally frequently, companies just sit on datasets that could power high value features, which would attract new customers.


Data is an intangible asset and deserves its own line on the enterprise balance sheet. Although there are costs associated with it, it can be a source of competitive advantage, intellectual property, and even revenue.

So therein concludes my tirade: until companies think strategically about data, nobody is going to buy the solutions that startups are peddling.
